spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.32.130:3306/gsc?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 100
      minimum-idle: 20
      max-lifetime: 120000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 当数据库字段使用_连接时这里配置成true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 配置日志
  mapper-locations: classpath*:/mapper/**/*.xml # 配置xml文件位置，这里是和@mapperscan注解的作用是不同的，后者是指定dao的位置
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
server:
  port: 8120
gsc:
  api-address:
    accurate:
      paths: http://localhost:8123/accurate/paths
    gedgnn:
      value-batch: http://localhost:8123/gedgnn/value_batch
      paths: http://localhost:8123/gedgnn/paths
    simgnn:
      value-batch: http://localhost:8123/simgnn/value_batch
    tagsim:
      value-batch: http://localhost:8123/tagsim/value_batch
  thread: # 线程池配置（IO密集型）
    core-size: 32
    max-size: 32
    keep-alive-time: 10
